name: Generate Certificates

on:
  push:
  
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install OpenSSL
        run: sudo apt-get update && sudo apt-get install -y openssl

      - name: Generate certificates
        run: |
          chmod +x make_cert.sh
          ./make_cert.sh ./cert_output

      - name: Upload certificates
        uses: actions/upload-artifact@v4
        with:
          name: certificates
          path: ./cert_output/
